### PR TITLE
ModFBX2ABC

### PR DESCRIPTION
**Pull request by janmroczkowski**
Model FBX to ABC converter

### CODE REVIEW

**Comment by lamiller0** [comment]
Thanks for the contribution!
Just letting you know we plan including this in 1.6.0.
Was it your intention to leave off the CMake file for fbx2abc? 
I'm not an FBX expert, so I don't have a good feel for how much of a pain introducing this would be.

**Comment by janmroczkowski** [comment]
CMake file for fbx2abc has not been done.
Fbx2abc was only built for Windows.
Visual Studio was used for that purpose directly without CMake.
Autodesk FBX SDK requires Visual Studio on Windows.

**Comment by meshula** [comment]
The code is good :)

You have probably thought of the following already, but I'll put it here in the thread for completeness:

Including this in Alembic would be a little problematic straight up, starting with FBX being a closed source library, and large. I'd suggest making the importer part of an optional contributed library, so as not to make it a required part of the build. There are linking implications on Unix-like OS's that are potentially pain points for people, which would be another good reason for it to be a contrib that can be built separately.

**Comment by sopvop** [comment]
I agree with @meshula.
(Sorry if I'm stealing thread) Compiling alembic is already painful as it is. I would even prefer if library and clients got split into different cmake projects.

**Comment by janmroczkowski** [comment]
I totally agree.
I was thinking of fbx2abc only building if one passes something extra to bootstrap, similar to maya plug-ins.

**Comment by lamiller0** [comment]
I've FINALLY had a chance to look closely at AbcJoin and noticed it had a dependency on boost::variant, std::experimental::string_view, std::experimental::optional, and libmv (for euclidean.h)?

Any chance that this code could be refactored to remove these dependencies?
If not, these tools could live in another github repo, and it could be advertised to users on alembic-discuss.

**Pull request closed without merging**
