### PR TITLE
Github Actions for Python 2.7 Wheel

### PR DESCRIPTION
**Pull request by digitalillusions**
Builds python wheel for the bindings of the current version of alembic on a manylinux2010 docker image and makes it available as a build artifact. This image is based on CentOS 6 and is supposed to have good compatibility with most current linux distributions. The actual compatibility remains to be tested.

Adresses #224

### CODE REVIEW

**Comment by digitalillusions** [comment]
See the artifact of this run for a sample wheel file https://github.com/digitalillusions/alembic/actions/runs/261690633

**Comment by lamiller0** [comment]
Thank you for the contribution!

Since this is your first one, would you mind filling out our CLA:
https://github.com/alembic/alembic/wiki/Alembic-Contributor-License-Agreements

And emailing it to me at:  miller.lucas+cla@gmail.com

**Comment by digitalillusions** [comment]
So I finally got around to testing the wheel on a Linux machine running Ubuntu 20.04 and for me it appears to work. @lamiller0 have you been able to test it as well?

**Comment by lamiller0** [comment]
Not yet! But I plan on including this in the next release, thanks!

**Comment by lamiller0** [comment]
I'm still trying to wrap my mind around Github Actions, how hard is it to launch the CMake tests for the different platforms?  This could potentially replace our current travis.cl setup.

**Comment by digitalillusions** [comment]
Should not be too hard. If you don't need anything "fancy" like I did with the docker container for the python wheel, you can just specify the system platform you want the CI to run on with the `runs-on` keyword, see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on, and specify the single commands that should be executed. 

I think you can just use a GitHub actions template to set up the pipelines for different platforms. If you want to check out how a "simple" CMake build process could look like, see https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/tree/master/.github/workflows for examples for both windows and linux. Essentially you can use GitHub Actions to just run single- or multi line commands with root access.

Let me know if there's anything in specific I can help with, by e.g. opening a new issue or sending me a mail.

**Pull request merged**
