### PR TITLE
Get Alembic plugin support "Variable crease edges"

### PR DESCRIPTION
**Pull request by alembicmaya**
This was the crease export written by Zhihao. In Maya, it makes the user to export a mesh to Alembic SubD easier.

CL 919189

o Add an export option -writeCreases to force writing a mesh as subd.

### CODE REVIEW

**Comment by lamiller0** [comment]
Wouldn't we be better served by an -autoSubd option instead?  That way if we detect creases, corners or holes on an MFnMesh that wasn't explicitly marked as a SubD it would write it out as one?

**Comment by zhihaoadsk** [comment]
Hey Lucas,
You means renaming the flag "-writeCreases" to "-autoSubd"? it sounds better and will cover more cases lika corners, holes :)
I think we need to update two aspects here:
1. rename the flag to  "-autoSubd"
2. make "-autoSubd" work for corner and holes except crease. to update MayaMeshWriter.cpp.

What do you think, Lucas?

**Comment by lamiller0** [comment]
Yes, renaming the flag to -autoSubd and having it create a subd if it detects creases, corners, or holes would be great!

**Comment by zhihaoadsk** [comment]
Thanks Lucas. We're going to update it soon. 

Zhihao

**Pull request merged**
