### PR TITLE
Remove MACOSX_RPATH forcing

### PR DESCRIPTION
**Pull request by mwestphal**
With cmake 3.0.0, CMP0042 applies and the default value of MACOSX_RPATH is true, this block is not needed anymore.

Setting this is a bad practice because in some cases one needs to disabled it.

### CODE REVIEW

**Comment by mwestphal** [comment]
@lamiller0 ?

**Comment by lamiller0** [comment]
Thanks for flagging this and providing the explanation.

Since this was your first contribution have you signed the Alembic CLA (or maybe you already work for a company that has signed that agreement), if not it can be found here:

https://github.com/alembic/alembic/wiki/Alembic-Contributor-License-Agreements

You can email it to miller.lucas+alembiccla@gmail.com

**Comment by mwestphal** [comment]
I'm an individual for this contribution, I will take a look this week.

**Comment by lamiller0** [comment]
Were you able to review and send out the CLA?

**Comment by mwestphal** [comment]
Completely forgot, Ill take a look.

**Comment by mwestphal** [comment]
[Sans titre_20230202_020514.pdf](https://github.com/alembic/alembic/files/10569362/Sans.titre_20230202_020514.pdf)

**Comment by lamiller0** [comment]
Thanks!

**Comment by mwestphal** [comment]
let me know if you need anything else from me to merge this.

**Comment by lamiller0** [comment]
We are good now, just need time to carve off the time to test and release.

**Pull request merged**
