### PR TITLE
Maya import particles

### PR DESCRIPTION
**Pull request by HansBaldzuhn**
Here is an implementation for animated particle import in maya.

The alembic feeds a nParticle shade connected to a Nucleus node.
The import gets attribute from the IPointSchema ( position, velocity, width ) and from all possible AbcGeoParam.

Export was also modified to correctly translate all user PP attribute into AbcGeomParam.

I am still not sure if IPoint width should be translated to radius or to 2*radius.

### CODE REVIEW

**Comment by lamiller0** [comment]
Hi, have you or your company signed the Alembic contributors agreement?

https://github.com/alembic/alembic/wiki/Alembic-Contributor-License-Agreements

**Comment by HansBaldzuhn** [comment]
Hi,
I sent a signed CLA by mail the 4th of April.

For the interpolation part, on my experience, it is extremely uncommon to have a constant point size. So I thought it could wait another round of commit if it were really needed.

Can you share you test file ? How did you generate it ? I was only able to test with particle export from maya and houdini.
Concerning my test files, they are all big files (aroung 1 Gb) What is the best way to share them ?

**Comment by lamiller0** [comment]
Would you mind emailing me the signed email as well?  I can make sure it's forwarded to the right people. (miller.lucas+cla@gmail.com)

I'll try to create you a smallish test file I can share.

The tests I had in mind don't need to be huge, just programatically created here:

https://github.com/alembic/alembic/blob/master/maya/Tests/animPointPrimitive_test.py

**Comment by HansBaldzuhn** [comment]
I just sent the CLA directly to you.
As for the test, I will put my maya test scene into a python script like in your exemple so we cant start on a working exemple.

**Comment by lamiller0** [comment]
The crash I hit was because my example lacked velocities. (which are optional)
You will also need to be careful of widths, if width is provided you are assuming there is one per point, but there are cases where just 1 width is provided for ALL points in the pointcloud.

**Comment by lamiller0** [comment]
Width is an IFloatGeomParam, so you can check the scope:
https://github.com/alembic/alembic/blob/master/lib/Alembic/AbcGeom/IGeomParam.h#L66
https://github.com/alembic/alembic/blob/master/lib/Alembic/AbcGeom/GeometryScope.h#L96

to see if it's constant or uniform, you could also just see how many values it had from what you read.

Velocities, and ids are regular array properties so IF they have data it is per point.

**Comment by lamiller0** [comment]
After more extensive reviewing I've found a bunch of potential issues with AbcImport.

Shouldn't the outPoints attr setStorable, writable, etc like some of the other attributes?
What is playFromCache for?

getPointArbGeomParamInfos reads every sample in case the extent wasn't set appropriately.  This will be horrible for large point caches with lots of samples.

Does this work for Alembic archives with multiple point clouds in it? It doesn't look like you are looping over all the point clouds in AlembicNode.

Is it also possible to reformat with spaces instead of tabs to be consistent with most of the other code?

**Comment by lamiller0** [comment]
Your tests sound reasonable, if you can't get radius working either let it fail (but have the check for it happen last) or add the check but comment it out, so we can ask Autodesk about it if necessary.

Make sure to add tests for both static and animated point clouds. (and multiple ones)

**Comment by HansBaldzuhn** [comment]
I finally made my tests work.

For getPointArbGeomParamInfos, this function should be called only on initialisation. It is necessary for arbGeom parsing when reading each frame.
Before trying to feed the nParticleShape, I must be sure that the data comming from the alembic file is correct and can be understood by maya.
So each arbGeomParam must be checked first. This check happens only once (either at import or at first read).

The overhead of the function should be minimal.

Also, the reason for the read of every sample is there because I cannot know if the extend is right. When dealing with houdini export, sometime I had a explicit extent of 1 when I had 300 sample with only 100 points. In this case, I assumed we actually have an extent of 3.
I started by checking only the first frame, but when the point clouds is empty on first frame, I cannot compute the actual number of points. I ended up looking for the frame with the most points.

The fact that the information on each param (extent, scope etc) can be wrong forces me to do a lot of check.
Actually, the scope is quite useless because we can't trust it to be correct. It's more safe to count the samples.

As for the extent, maybe there is an easier solution to check the extent ? Is there some property I can rely on ?

**Comment by HansBaldzuhn** [comment]
I just pushed a new version, with a new test in maya: animPointPrimitive_nParticle_test

It has test for 3 different nParticle setups that includes:
- varying width and uniform width
- constant and uniform custom attributes
- multiple nParticle in the same export

Also about this multiple point cloud, you are right, the loop doesn't occur inside the AlembicNode::compute(), it occurs during maya dg evaluation.

The way the compute handles the data for polygon an other types forces an evaluation of the entire array, even if only one object is marked as dirty.
This can be bad when the alembic file has 1000 primitive but the user has hidden 999 of them. On each frame, the dependency graph will mark the visible primitive as dirty and call for an update.
The compute method will be triggered and will read and update all 1000 primitive because of the forced loop.

When implementing Points for maya, I made a different approach. 
When a user action asks for an update of a particle shape (changing frame most of the time), it will mark this particular nParticle as dirty, and call the compute methode. It will only read and update the plug corresponding to the dirty nParticle object .
If multiple nParticle are set dirty, the compute method will be called once per nParticle.

There might be a little overhead when you want all Points Cloud to be updated (because of multiple compute call instead of one), but one usually want to have an improvement in playback speed when hiding unwanted elements. I think this is more important but we could discuss on that.

**Comment by lamiller0** [comment]
The purpose of the extent and scope is to avoid having to check the size of it to confirm.
If it isn't accurate in the official Houdini writer you should report the issue to SideFX so they can fix the writer on there end.

Some of the arbitrary data can be quite big, if you have a color for every point in a 10 million point particle system, and it has 1000 frame, it doesn't make sense to do all that reading.

There are ways to get just the size which would be a bit better, but it's best to rely on scope and extent, and do the best you can with the data that is actually returned.

**Comment by HansBaldzuhn** [comment]
Hi Lucas,

I push a new version, I removed the expensive check in favor of a simple ignore with warning when a strange sample is found (incorrect extent or incorrect number of points in a sample).

Also, to be able to test uniform and constant value on export and import, I made a small "routing" of user attributes to geomParam.
The only way I had to create uniform and constant attribute in maya was to create custom attributes on the nParticleShape ans to specify them in the job argument.
But with this method, the atteibutes are not writtent to arbGeomParam si they are not part of the point cloud data.
So, when looking for userAttribute on alembic export, if such an attribute is found on a nParticleShape, it is written instead to arbGeom.
This behaviour could be removed for next versions but it is nescessary now for test purpose.

**Comment by lamiller0** [comment]
Thanks!  I hope to review this again soon.

**Comment by lamiller0** [comment]
Animated point clouds seems to be working fairly well right now.  Would it be hard to support static ones? (happens to only have 1 frame)

The hierarchy loads, but no particles show up.

The compiler also compiled about a couple of small things, but I can fix that after accepting the merge.

**Comment by HansBaldzuhn** [comment]
I will investigate static point cloud. I will add a new test with this particular case.
Where is your static data exported from ? I will try with a one frame export from maya but I'm not sure it's going to have the same behaviour.
Right now on export I assumed that particles are always animated because it is extremly hard to know if they move or not. And there is no way that I know in maya to specify static particles. Even when "is dynamic" is off, they might move with an expression, a cache or a deformer.

In an alembic point of view, is an animated property with one sample equivalent to a static property ?

**Comment by lamiller0** [comment]
A one frame export will work.

Also this test will create it:

https://github.com/alembic/alembic/blob/master/maya/Tests/staticPointPrimitive_test.py

Although the properties it's checking are probably now incorrect.

**Comment by BigRoy** [comment]
Hi @HansBaldzuhn, how is this coming along? Looking forward to some decent particle support in Maya. :smile: Are you still actively working on this?

**Comment by HansBaldzuhn** [comment]
Since the last update from autodesk on the maya part of the code, I cannot
compile anymore.
I need to update my setup to support C++11 but my setup is on centos 6.
I didn't took the time to see how I can update or workaround this issue.
It took me so long to have a working setup with alembic, maya and git that
I dropped for the moment, until I have enough motivation to convert my
setup toC++11.

**Comment by HansBaldzuhn** [comment]
Here is an update with multiple unittest that works with constant point clouds
I tested the code without the override keyword to bypass the C++11 support.

**Comment by lamiller0** [comment]
Thanks, testing on these updates has been going well.
There are a handful of warnings about unused variables that got flagged, but I can take care of those.

**Comment by HansBaldzuhn** [comment]
I don't have warning on my side, can you share some of them ? My compiler might not be strict enough.
I will change my settings for next time, sorry.

**Comment by BigRoy** [comment]
I've recently compiled Alembic `1.7.12` and I am getting a crash in Maya 2019.2 when importing an Alembic that has exported nParticles in it.

```
Stack trace:
  OpenMaya.dll!THdependNode::computePlug
  DependEngine.dll!TevaluationNode::evaluateDirtyPlugs
  DependEngine.dll!TevaluationNode::taskEvaluation
  DependEngine.dll!TparallelExecution::evaluateAndVisitChildren
  DependEngine.dll!TparallelExecution::evaluateAndSchedule
  DependEngine.dll!TparallelExecution::sAddNodesWithinDepthToSet
  tbb.dll!tbb::interface7::internal::task_arena_base::internal_execute
  DependEngine.dll!TparallelExecution::evaluateImplementation
  DependEngine.dll!TevaluationGraph::evaluate
  DependEngine.dll!TevaluationManager::evaluate
  DependEngine.dll!TcipEvaluationManager::operator=
  DependEngine.dll!TdependGraph::setTime
  Shared.dll!TfrozenEvaluator::sProcessDownstream
  ExtensionLayer.dll!TidleAction::preDoIdleAction
  ExtensionLayer.dll!TarrayTdeviceHandlerPtr::size
  ExtensionLayer.dll!TperiodElapsedMsg::operator=
  ExtensionLayer.dll!TeventHandler::doIdles
  ExtensionLayer.dll!TidleLicenseAction::doIdleAction
  Qt5Core.dll!QObject::event
  Qt5Widgets.dll!QApplicationPrivate::notify_helper
  Qt5Widgets.dll!QApplication::notify
  ExtensionLayer.dll!TwindowManager::windowPreferencesAreEnabled
  Qt5Core.dll!QCoreApplication::notifyInternal2
  Qt5Core.dll!QEventDispatcherWin32::event
  Qt5Widgets.dll!QApplicationPrivate::notify_helper
  Qt5Widgets.dll!QApplication::notify
  ExtensionLayer.dll!TwindowManager::windowPreferencesAreEnabled
  Qt5Core.dll!QCoreApplication::notifyInternal2
  Qt5Core.dll!QCoreApplicationPrivate::sendPostedEvents
  qwindows.dll!qt_plugin_query_metadata
  Qt5Core.dll!QEventDispatcherWin32::processEvents
  USER32.dll!CallWindowProcW
  USER32.dll!DispatchMessageW
  Qt5Core.dll!QEventDispatcherWin32::processEvents
  qwindows.dll!qt_plugin_query_metadata
  Qt5Core.dll!QEventLoop::exec
  Qt5Core.dll!QCoreApplication::exec
  ExtensionLayer.dll!Tapplication::start
  maya.exe!<7FF7DFA777A8>
  maya.exe!TiteratorWrapperFwd<TscenePartitions::ConstIteratorDescriptor,TiteratorWrapper<TscenePartitions::ConstIteratorDescriptor> >::operator++
```

Related crash log:
[MayaCrashLog191123.1523.log](https://github.com/alembic/alembic/files/3882543/MayaCrashLog191123.1523.log)

This is the `.abc` file I quickly exported. (Just created nParticle emitter, select shape, export timeline):

[particles.zip](https://github.com/alembic/alembic/files/3882544/particles.zip)

---

Has anyone tested this functionality in production? Or am I doing something wrong?
Should I make an issue about this?

**Pull request merged**
