### PR TITLE
Fixed wstring array hashing

### PR DESCRIPTION
**Pull request by ahmidou**

### CODE REVIEW

**Comment by lamiller0** [comment]
Hi, Thanks for the bug fix, I don't recognize your name in our list of Alembic contributors.
Have you previously signed the individual contributors agreement (https://docs.google.com/file/d/0B_S7TABLaH6xanl2X2xsMGowZFk) or work for an organization the has signed the corporate agreement?

**Comment by ahmidou** [comment]
Hi Lucas,
Indeed, I'm not an Alembic contributor, so here's the signed agreement. I
was also wondering, as I'm updating the Softimage Alembic plugin done by
Autodesk (currently hosted on source forge/google code
<http://softimage-alembic-plugin.sourceforge.net/>) would you accept a pull
request with the plugin sources ?

2015-01-07 19:34 GMT-05:00 Lucas Miller <notifications@github.com>:

**Comment by lamiller0** [comment]
Sadly the attached contributors agreement doesn't appear to be filled out.

Because of SoftImage's End of Life status, and since it isn't widely used
and supported by the primary Alembic contributors I don't think there is
much of an appetite to officially bring it into the project and keep it
maintained.

**Comment by ahmidou** [comment]
Are you sure? For some reasons Gmail kept the one you sent me in plus of
the one I filled, so you should have both attached.
That's Ok for the softimage plugin, I'll keep it on my branch then.

Cheers
-A

2015-01-08 13:07 GMT-05:00 Lucas Miller <notifications@github.com>:

**Comment by lamiller0** [comment]
I double checked and I'm only seeing the blank pdf, maybe Github strips the
attachment, but the original showed up because it is shared via a link to
Google Drive?

**Comment by lamiller0** [comment]
I've been informed that emailing your contributors agreement directly to contributors@alembic.io is an awesome thing to do!

**Comment by ahmidou** [comment]
It'd done :)
Thanks Lucas!

-A

2015-01-08 14:21 GMT-05:00 Lucas Miller <notifications@github.com>:

**Pull request merged**
