### PR TITLE
Use FIND_PACKAGE macro to handle GLEW

### PR DESCRIPTION
**Pull request by nyue**
Use Find_Package macro to handle GLEW rather than hard coding as it becomes difficult to maintain in the long run.
I don't have a Windows box to verify so I didn't modify the hard coded library names still lurking in the Win32 block.

### CODE REVIEW

**Comment by nyue** [comment]
Also added installation target for abcls and abctree

**Comment by lamiller0** [comment]
In my builds with the bootstrap I'm getting:

CMake Error at CMakeLists.txt: 196 (FIND_PACKAGE):
Could not find module FindGLEW.cmake or a configuration file for package GLEW.

Adjust CMAKE_MODULE_PATH to find FindGLEW.cmake or set GLEW_DIR to the directory containing a Cmake configuration file for GLEW.  The file will have one of the following names:

GLEWConfig.cmake
glew-config.cmake

**Comment by lamiller0** [comment]
I've read that GLEWConfig.cmake is only included from 2.8.10 onward.

**Comment by nyue** [comment]
I see.

Current CMake is at 3.x so I guess requiring 2.8.10 as a minimal may be reasonable. I think the latest for 2.x is now 2.8.12.2

I believe RedHat/CentOS ships with 2.8.10, I may be wrong.

**Comment by lamiller0** [comment]
As there is some planned work on how Alembic is built. (fewer libraries, better multiplatform dynamic lib support)  changing the CMake version requirement for that work seems much more reasonable.

What version of CMake are you using?

**Comment by nyue** [comment]
Good to hear about build improvements.
I mostly use CMake v2.8.12.2, minimum version is CMake v2.8.11 on CentOS 6.4 on our production pipeline.

**Comment by lamiller0** [comment]
I think this was addressed in the big CMake update that just got pushed.

**Pull request closed without merging**
