### PR TITLE
CMake: relocatable shared lib for macOS

### PR DESCRIPTION
**Pull request by SpaceIm**
Remove hardcoded `CMAKE_POLICY(SET CMP0042 OLD)`. This policy is NEW by default since CMake 3.0 and it's a good default since it allows to install relocatable shared libs on macOS.

### CODE REVIEW

**Comment by lamiller0** [comment]
Hi, thank you for your contributions.

Before I can accept them, please fill out the appropriate CLA here:
https://github.com/alembic/alembic/wiki/Alembic-Contributor-License-Agreements

And email a copy to:
miller.lucas+cla@gmail.com

If you happen to be contributing for a company that may already have signed a corporate CLA, please let me know.

**Comment by SpaceIm** [comment]
It's asking for too much information, I can't sign this.

**Comment by lamiller0** [comment]
Thats okay, I can use your 2 PRs to create a new one inspired by what they were doing.

**Comment by lamiller0** [comment]
Added to #457

**Pull request closed without merging**
