### PR TITLE
Windows dll

### PR DESCRIPTION
**Pull request by jproccia**
Hi,

I'm Jean-Patrick Roccia from Isotropix.

I made some developments to handle cross-platform static/dynamic libraries build in Alembic.
The branch has been tested on : 
  -CentOS 6 x64 (GCC 4.8.2)
  -Mac OS X 10.8.5 (GCC 4.2.1)
  -Windows 7 x64 (Visual studio 2013)

For each system, Alembic has been built using CMake, in both static/dynamic libraries mode. I've been able to load and visualize our Alembic files with the simple viewer on all systems and configurations.

By default, Alembic is now built in dynamic libraries mode. 
In order to switch mode, you have to set the CMake variable ALEMBIC_SHARED_LIBS.
Concretely, if ALEMBIC_SHARED_LIBS is true (default) you will obtain dynamic libraries(.so/.dylib/.dll), else static libraries (.a/.a/.lib).

I also made some adjustments on openexr link flags for windows (when using openexr dll), and other fixes to compile under windows.

Here are my CMake build commands by systems :
- Windows
cmake -G"Visual Studio 12 Win64" ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=F:/alembic/install_dir -DGLEW_INCLUDE_DIR=F:/glew-1.11.0/include -DGLEW_LIBRARY=F:/glew-1.11.0/lib/release/x64/glew32s.lib -DGLUT_INCLUDE_DIR=F:/freeglut-2.8.1/include -DGLUT_glut_LIBRARY=F:/freeglut-2.8.1/lib/x64/freeglut.lib -DZLIB_INCLUDE_DIR=F:/zlib-1.2.8/install_dir/include -DZLIB_LIBRARY=F:/zlib-1.2.8/install_dir/lib/zlibstatic.lib -DILMBASE_ROOT=F:/openexr/IlmBase/install_dir -DHDF5_C_LIBRARY=F:/hdf5-1.8.14/install_dir/lib/libhdf5.lib -DHDF5_DIR=F:/hdf5-1.8.14/install_dir/cmake/hdf5  -DBOOST_ROOT=F:/boost_1_55_0 -DALEMBIC_GLEW_LINK_STATIC=1 -DUSE_PRMAN=0 -DUSE_ARNOLD=0 -DUSE_MAYA=0 -DUSE_PYALEMBIC=0 -DALEMBIC_SHARED_LIBS=1

- Mac OS
cmake -G"Unix Makefiles" ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install_dir -DZLIB_INCLUDE_DIR=/Users/jproccia/3rdparty/zlib-1.2.8/install_dir/include -DZLIB_LIBRARY=/Users/jproccia/3rdparty/zlib-1.2.8/install_dir/lib/libz.a -DILMBASE_ROOT=/Users/jproccia/3rdparty/ilmbase-2.2.0/install_dir -DHDF5_DIR=/Users/jproccia/3rdparty/hdf5-1.8.14/install_dir/share/cmake/hdf5/ -DBOOST_ROOT=/Users/jproccia/3rdparty/boost_1_55_0/ -DALEMBIC_GLEW_LINK_STATIC=1 -DUSE_PRMAN=0 -DUSE_ARNOLD=0 -DUSE_MAYA=0 -DUSE_PYALEMBIC=0 -DALEMBIC_SHARED_LIBS=1

- Linux
cmake -G"Unix Makefiles" ../ -DCMAKE_INSTALL_PREFIX=/home/jproccia/Code/alembic/install_dir -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/home/jproccia/Code/boost_1_55_0 -DILMBASE_ROOT=/home/jproccia/Code/openexr/IlmBase/install_dir/ -DUSE_PRMAN=0 -DUSE_ARNOLD=0 -DUSE_MAYA=0 -DUSE_PYALEMBIC=0 -DALEMBIC_SHARED_LIBS=1

Hope this will help Alembic community :)

### CODE REVIEW

**Comment by jproccia** [comment]
Hi, 
agreed with your comments on further steps : 
 - Add compilation flag -fvisibility=hidden and specify visibility ("default") for exported symbols on Linux/OSX 
- Merge libraries. It only implies to reduce the number of export headers on the export side, but I don't know the implications in the CMake build system if the conceptual build tree is preserved.

Right now, I don't have the time to test seriously on three platforms again, so I prefer to keep this pull request in a stable state. I think those steps can be made after the merge. in order to bring to everyone the static/shared cross-platform build, even if it can be improved. 

On your side, do you see some reason to delay the merge?

**Comment by lamiller0** [comment]
We are still weighing whether the appropriate resources will be freed up in a timely manner to address the further steps.

**Comment by jproccia** [comment]
Hi,

I just took a look to your dev branch.
Great job, I don't know if you have finished, but I prefer to warn you about something.
As mentioned before, I think that only one header for all library exports is problematic.
I just compared exported symbols of windows dll of this implementation vs mine. 
For example, my version of AlembicAbcCoreFactory exports 15 symbols, when the new version exports 188 symbols.
This doesn't seems right. 
I think that, on Windows the dllimport/dllexport must be defined per dll.
Currently, each include file of an other dll header triggers symbol export in the current dll. 
To illustrate this, AlembicAbcCoreFactory.dll exports all included Alembic::util symbols in your dev branch.

As I said before, if the output is reduced to only one dll, this problem is solved, because symbols are exported once.
But right now, on windows, same symbols are exported multiple times in different dll.

Let me know if I'm wrong or if my explanation is not clear.

**Comment by rsgalloway** [comment]
Hey Jean-Patrick, thanks for testing, and you're right: the build-dev branch is not quite complete and the merge libraries step is still forthcoming. Perhaps I should have closed this PR earlier at edf79df1c, or waited until the library merging was done, depending on whether features raised in the comments are viewed as being included as part of the PR or not. If you guys feel we should re-open the PR until the library merging is done, I'm OK with that.

**Comment by jproccia** [comment]
Well, I don't mind the PR state. 
I just wanted to be sure that the current dev was not final because it requires library merging to be completed (on windows).
Anyway, thanks for details.

**Comment by meshula** [comment]
The current Alembic export set up looks pretty similar to what we have in OpenEXR (pasted below as typical). What Jean-Patrick describes sounds like maybe the per-DLL export macros are not set up uniquely per DLL?


#ifndef HALFEXPORT_H
#define HALFEXPORT_H

//
//  Copyright (c) 2008 Lucasfilm Entertainment Company Ltd.
//  All rights reserved.   Used under authorization.
//  This material contains the confidential and proprietary
//  information of Lucasfilm Entertainment Company and
//  may not be copied in whole or in part without the express
//  written permission of Lucasfilm Entertainment Company.
//  This copyright notice does not imply publication.
//

#if defined(PLATFORM_WINDOWS)
#  if defined(PLATFORM_BUILD_STATIC)
#    define PLATFORM_EXPORT_DEFINITION 
#    define PLATFORM_IMPORT_DEFINITION
#  else
#    define PLATFORM_EXPORT_DEFINITION __declspec(dllexport) 
#    define PLATFORM_IMPORT_DEFINITION __declspec(dllimport)
#  endif
#else   // linux/macos
#  if defined(PLATFORM_VISIBILITY_AVAILABLE)
#    define PLATFORM_EXPORT_DEFINITION __attribute__((visibility("default")))
#    define PLATFORM_IMPORT_DEFINITION
#  else
#    define PLATFORM_EXPORT_DEFINITION 
#    define PLATFORM_IMPORT_DEFINITION
#  endif
#endif

#if defined(HALF_EXPORTS)                          // create library
#  define HALF_EXPORT PLATFORM_EXPORT_DEFINITION
#else                                              // use library
#  define HALF_EXPORT PLATFORM_IMPORT_DEFINITION
#endif

#endif // #ifndef HALFEXPORT_H

**Comment by rsgalloway** [comment]
There were unique in my first commit, edf79df, which is where we probably should have closed this PR. I merged the exports in 673c519 in anticipation of merging the libs, but missed a couple of the visibility attributes, which I added in 66d4f82. I am now working on merging the libs into a single libAlembic.so/dll.

**Comment by meshula** [comment]
Ah, that sounds cool :)

**Pull request closed without merging**
