### PR TITLE
Custom python

### PR DESCRIPTION
**Pull request by smaragden**
I have for some releases always patched the alembic build system to work with custom python installations. This pull request makes it possible to to specify a PYTHON_ROOT variable to build against a custom python installation without breaking old behavior.

It is only tested on linux/centos7 for now, but i will verify it on OSX and update it accordingly.

I don't have the possibility to test it on windows and could need some help with that.

I also moved all python configuration to the cmake/AlembicPython.cmake file.

Please tell me what you think.

### CODE REVIEW

**Comment by smaragden** [comment]
Just realized that as soon as you have python-devel package installed the FindPythonLibs will always find that one instead.
I need to write more cmake code to handle this.
I will update this PR accordingly.

**Comment by sopvop** [comment]
~~~~
-DPYTHON_LIBRARY=/path/to/libpython.so
-DPYTHON_INCLUDE_DIR=/path/to/folder/with/Python.h
-DPYTHON_EXECUTABLE=/python/to/python
~~~~

Please stop this madness with every cmake project using custom named variables and custom modules for finding stuff when there are standard ones available.

**Comment by smaragden** [comment]
>Please stop this madness with every cmake project using custom named variables and custom modules for finding stuff when there are standard ones available.

I agree it is madness. But if FindPythonInterp and FindPythonLibs would work as expected on all platforms in all situations it would be fine.

The convention for this repo to define 3rd party dependencies seems to have been unified to <PREFIX>_ROOT. That's why i tried to do that for python as well.

We still need to rewrite how alembic finds python.
Right now the code is scattered between:
CMakeLists.txt
cmake/AlembicPython.cmake
python/PyAbcOpenGL/CMakeLists.txt
python/PyAlembic/CMakeLists.txt

I'm on centos 7(cmake 2.8.11) and FindPythonLibs seems to work as expected.
Maybe i should just move all python finding code to cmake/AlembicPython.cmake, and only use FindPythonLibs. And we will see if the problems that created all this workaround code in the first place re-surfaces.

**Comment by smaragden** [comment]
I'm closing this PR now and create a new one when I have a solution that works on all platforms.

**Pull request closed without merging**
