### PR TITLE
Allow specifying the exact install prefix using CMAKE_INSTALL_PREFIX

### PR DESCRIPTION
**Pull request by chadrik**
Previously,  alembic-${VERSION} was appended to CMAKE_INSTALL_PREFIX.  With this change, the append behavior is only used if you set ALEMBIC_INSTALL_PREFIX.

Fixes Issue #44

### CODE REVIEW

**Comment by lamiller0** [comment]
This looks reasonable.

**Comment by rsgalloway** [comment]
without defining CMAKE_INSTALL_PREFIX, it'll default to /user/local, correct? Not /usr/local/alembic. So a make install would write the files to /usr/local/libAlembic.so, is that right?

**Comment by chadrik** [comment]
From the cmake docs

> This variable defaults to /usr/local on UNIX and c:/Program Files on Windows.

I think it would install to /usr/local/**lib/**libAlembic.so.

Are you concerned about that being a bad default?  I find that's the default behavior for most libraries.

**Comment by rsgalloway** [comment]
Thanks. No, not concerned, just wanted clarity and to make sure we're all in agreement about what it should do. If that's the case, then this seems fine to merge as-is.

**Pull request merged**
