### PR TITLE
Cmake config file

### PR DESCRIPTION
**Pull request by lamiller0**
Use a CMake config file to determine if we built with HDF5, whether we are using, boost, tr1, or c++11 (default) for things like the shared_ptr.

May address C++11 Mac Yosemite issues?

Instead of using TARGET_OBJECT we gather our sources for the main Alembic lib in the hopes that we can compile a dll in Windows. (needs more testing)

### CODE REVIEW

**Comment by meshula** [comment]
What are the Yosemite issues you're seeing?

**Comment by lamiller0** [comment]
It was to address your report that you needed to hardcode -std=c++11 for Xcode 6.3.1

**Comment by meshula** [comment]
Ok, thanks :) I don't know how to pull a patch from github, but I'm happy to test this against my build, if someone tells me how!

**Comment by rsgalloway** [comment]
@meshula Thanks, Nick. You can pull Lucas' branch directly from his clone, 
```
git clone https://github.com/lamiller0/alembic
git fetch
git checkout cmake_config_file
```
or just merge it into your Alembic repo like this:
```
git checkout -b lamiller0-cmake_config_file master
git pull git://github.com/lamiller0/alembic.git cmake_config_file
```
I'm pullling and testing this now, also.

**Comment by meshula** [comment]
I was able to remove the c++11 hack from my build script :) Thanks :)

**Pull request merged**
